language: php

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 5

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install -vvv --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
