name: "PHPStan"

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.5"

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: ramsey/composer-install@v4
        with:
          dependency-versions: highest

      - name: Run PHPStan
        run: |
          composer require --dev phpunit/phpunit:^9.6 --with-all-dependencies
          vendor/bin/phpstan analyse
