name: "PHPStan"

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          # pinned to 7.4 because we need PHPUnit 7.5 which does not support PHP 8
          - "7.4"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: highest

      - name: Run PHPStan
        # Locked to phpunit 7.5 here as newer ones have void return types which break inheritance
        run: |
          composer require --dev phpunit/phpunit:^7.5.20 --with-all-dependencies ${{ env.COMPOSER_FLAGS }}
          vendor/bin/phpstan analyse
